version: "3.8"

services:
    app:
        build: ./app
        ports:
            - "5000:5000"
        links:
            - db
        deploy:
            resources:
                 limits:
                     cpus: '0.50'
                     memory: 8G
                 reservations:
                     cpus: '0.25'
                     memory: 4G
    db:
        build: ./db